// Copyright (c) 2024-2025 The Khronos Group Inc.
// Copyright (c) 2024-2025 Valve Corporation
// Copyright (c) 2024-2025 LunarG, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// NOTE: This file doesn't contain any entrypoints and should be compiled with the --no-link option for glslang

#version 450
#extension GL_ARB_gpu_shader_int64 : require

// This is linked in and reset once per function
uvec4 invalid_alignment;

void inst_buffer_device_address_alignment_check(
    const uint64_t addr,
    const uint alignment,
    const uint inst_num)
{
    if ((addr & (alignment - 1)) != 0) {
        invalid_alignment = uvec4(uint(addr), uint(addr >> 32u), alignment, inst_num);
    }
}
